export * from './Header'
export * from './MoviesContainer'
export * from './GenresContainer'
export * from './Swicher'
export * from './GenresOfMoviesContainer'
export * from './MovieDetailsContainer'
export * from './PaginationsContainer'
export * from './SerchesContainer'